# https://docs.docker.com/compose/compose-file/
version: '3.6'
services:
  app:
    build: .
    environment:
      DATABASE_URL: "postgesql://elixir:password@postgres/ex_venture"
      HOST: "example.com"
      PORT: 4000
      POOL_SIZE: 5
      SECRET_KEY_BASE: "nSUzQ0L9DLDjAacQZKnG11NAZf+26wU75zVGKq4FxUgRRMeorJA7Os2giqvBINiN"
      URL_PORT: 4000
      URL_SCHEME: http
    depends_on:
      - postgres
    ports:
      - 4000:4000

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ex_venture
      POSTGRES_PASSWORD: password
      POSTGRES_USER: elixir
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
