apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kantele.fullname" . }}
  labels:
    {{- include "kantele.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      {{- include "kantele.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kantele.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: telnet
              containerPort: 4444
              protocol: TCP
            - name: http
              containerPort: 4500
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
